trigger:
- main

pool: linuxAgentPool

stages:
  - stage: A
    jobs:
      - job: job1
        steps:          
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'sudo apt install ansible -y'