trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
  
  - script: 'git clone https://github.com/akash66sheoran/ansible-demo-repo.git'

  - script: 'ls $(Agent.BuildDirectory)'

  - script: 'ls $(Build.SourcesDirectory)'