trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - script: 'git clone https://github.com/akash66sheoran/ansible-demo-repo.git'

  - script: 'rm -rf $(Build.SourcesDirectory)/*'